blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'
urlpatterns = [
    path(
        '',
        views.post_list,
        name='post_list'
    ),
    path(
        'tag/<str:tag_slug>/',
        views.post_list, name='post_list_by_tag'
    ),
    path(
        '<int:year>/<int:month>/<int:day>/<str:slug>/',
        views.post_detail,
        name='post_detail'
    )
]

tunasite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]
 

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

from taggit.managers import TaggableManager

from hashlib import md5


class Post(models.Model):
    STATUS_CHOICES = [
        ('DRAFT', 'Draft'),
        ('PUBLISHED', 'Published'),
    ]
    title = models.CharField(max_length=250)
    slug = models.SlugField(
        max_length=250, 
        unique_for_date='publish'
    )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='DRAFT'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts'
    )
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    username = models.CharField(max_length=120)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.username, self.post)

    def avatar(self, size=60):
        md5_digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(md5_digest, size)

blog/forms.py
from django import forms
from django.forms import TextInput, Textarea
from blog.models import Comment


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('username', 'email', 'body')       
        widgets = {
            'username': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
            'body': Textarea(attrs={'class': 'form-control', 'rows': 4})
        }

blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from blog.models import Post, Comment
from blog.forms import CommentForm

from taggit.models import Tag

def post_list(request, tag_slug=None):
    if tag_slug:
        tag = Tag.objects.filter(slug=tag_slug).first()
        post_list = Post.objects.filter(tags__in=[tag])
    else:
        post_list = Post.objects.all()

    tag_list = Tag.objects.all()
    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(
        request,
        'blog/post/list.html',
        {
            'posts': posts,
            'tag_list': tag_list
        }
    )

def post_detail(request, year, month, day, slug):
    post = Post.objects.filter(
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug
    ).first()
    comments = post.comments.filter(active=True)
    new_comment = None
    comment_form = CommentForm
    tag_list = Tag.objects.all()

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        return redirect(request.path_info)

    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'tag_list': tag_list
        }
    )

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:post_list' %}">Tuna's Blog</a>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <!-- Blog Entries Column -->
      <div class="col-md-8">
        {% block content %}
        {% endblock %}
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-3">

        <!-- Search Widget -->
        <!-- <div class="card mb-3">
          <h5 class="card-header">Search</h5>
          <div class="card-body">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div> -->

        <!-- Categories Widget -->
        <div class="card mb-3">
          <h5 class="card-header">Tags</h5>
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6">
                <ul class="list-unstyled mb-0">
                  {% for tag in tag_list %}
                  <li>
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }} ({{ tag.taggit_taggeditem_items.count }})</a>   
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; <script type="text/javascript">document.write(new Date().getFullYear())</script> Tuna Hsu</p>
    </div>
    <!-- /.container -->
  </footer>

</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block content %}

<!-- Blog Post -->
<div class="row">

  <!-- Post Content Column -->
  <div class="col-lg-10">

    <!-- Title -->
    <h1 class="mb-4">{{ post.title }}</h1>

    <!-- Date/Time/Author -->
    <hr>
    <p>
      Posted on {{ post.publish }} by 
      <a href="#">{{ post.author }}</a>
    </p>
    <hr>

    <!-- Post Content -->
    <p>
      {{ post.body|linebreaks }}
    </p>

    <!-- Comment with nested comments -->
    <h4>{{ comments.count }} comment{{ comments.count|pluralize }}</h4>
    {% for comment in comments.all %}
    <hr>
    <div class="media mb-4">
      <img class="d-flex mr-3 rounded-circle" src="{{ comment.avatar }}" alt="">
      <div class="media-body">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mt-0">{{ comment.username }}</h5>
          <span>{{ comment.created|timesince }} ago</span>
        </div>

        {{ comment.body|linebreaks }}

        <!-- <div class="media mt-4">
          <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
          <div class="media-body">
            <h5 class="mt-0">Commenter Name</h5>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div> -->
      </div>
    </div>
    {% endfor %}

    <!-- Comments Form -->
    <div class="card my-4">
      <h5 class="card-header">Leave a Comment:</h5>
      <div class="card-body">
        <form action="." method="POST">
          {% for field in comment_form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field.label_tag }} {{ field }}
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
          {% endfor %}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>

  </div>
</div>
<!-- /.row -->

<!-- Similar posts -->
<div class="">
  <!-- <h2>Similar posts</h2>
  {% for post in post.tags.similar_objects %}
    <p>
      <a href="{{ post.get_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
      There are no similar posts yet.
  {% endfor %} -->

</div>

{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block content %}

{% for post in posts %}
  <!-- Blog Posts -->
  <div class="card mb-4">
    <div class="card-body">
      <h2 class="card-title">{{ post.title }}</h2>
      <p class="card-text">{{ post.body|truncatewords:30|linebreaks }}</p>
      <a href="{{ post.get_url }}" class="btn btn-outline-secondary">Read More &rarr;</a>
    </div>
    <div class="card-footer text-muted">
      Posted on {{ post.publish }} by
      <a href="#">{{ post.author }}</a>
    </div>
    {% if post.tags.count %}
      <div class="card-footer text-muted">
        Tags: 
        {% for tag in post.tags.all %}
          <a href="{% url 'blog:post_list_by_tag' tag.slug %}" class="badge badge-light">{{ tag.name }}</a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
{% endfor %}

<!-- Pagination -->
<ul class="pagination justify-content-center mb-4">
  {% if posts.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ posts.previous_page_number }}">&larr; Older</a>
    </li>
  {% endif %}
  {% if posts.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ posts.next_page_number }}">Newer &rarr;</a>
    </li>
  {% endif %}
</ul>

{% endblock %}